// <auto-generated />
using System;
using EngenhariasSenac.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngenhariasSenac.Migrations
{
    [DbContext(typeof(EngenhariasSenacContext))]
    [Migration("20250513184339_AddEntitiesLoginLog")]
    partial class AddEntitiesLoginLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectTeam", b =>
                {
                    b.Property<int>("CodTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTeam"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Leader")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CodTeam");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Student", b =>
                {
                    b.Property<int>("CodStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodStudents"));

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdSenac")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PointMaterial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectTeam")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("CodStudents");

                    b.HasIndex("IdSenac")
                        .IsUnique()
                        .HasFilter("[IdSenac] IS NOT NULL");

                    b.HasIndex("InstitutionalEmail")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.StudentLoginLog", b =>
                {
                    b.Property<int>("CodStudentLoginLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodStudentLoginLog"));

                    b.Property<int>("CodStudent")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtTmAccess")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtTmEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodStudentLoginLog");

                    b.ToTable("StudentLoginLog");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Teacher", b =>
                {
                    b.Property<int>("CodTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTeacher"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstitutionalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodTeacher");

                    b.HasIndex("InstitutionalEmail")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.TeacherLoginLog", b =>
                {
                    b.Property<int>("CodTeacherLoginLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTeacherLoginLog"));

                    b.Property<int>("CodTeacher")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtTmAccess")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtTmEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodTeacherLoginLog");

                    b.ToTable("TeacherLoginLog");
                });
#pragma warning restore 612, 618
        }
    }
}
