// <auto-generated />
using System;
using EngenhariasSenac.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngenhariasSenac.Migrations
{
    [DbContext(typeof(EngenhariasSenacContext))]
    [Migration("20250527182018_EditLecuresData")]
    partial class EditLecuresData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EngenhariasSenac.Models.BusinessAssessment", b =>
                {
                    b.Property<int>("CodAssessment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAssessment"));

                    b.Property<decimal>("Assessment")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyEvaluated")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudentEvaluator")
                        .HasColumnType("int");

                    b.HasKey("CodAssessment");

                    b.ToTable("BusinessAssessment");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Companies", b =>
                {
                    b.Property<int>("CodCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCompany"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodCompany");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CodCompany = 1,
                            Description = "Empresa especializada em soluções de mobilidade elétrica e urbana.",
                            Name = "Eforce Mobilidade",
                            Picture = "/public/pictures/business/eforce_mobilidade.jpg"
                        },
                        new
                        {
                            CodCompany = 2,
                            Description = "Indústria focada em usinagem de precisão e corte CNC de alta performance.",
                            Name = "Fiber CNC",
                            Picture = "/public/pictures/business/fiber_cnc.jpg"
                        },
                        new
                        {
                            CodCompany = 3,
                            Description = "Grupo empresarial com atuação no setor de distribuição e atacado.",
                            Name = "Grupo CBD",
                            Picture = "/public/pictures/business/grupo_cbd.jpg"
                        },
                        new
                        {
                            CodCompany = 4,
                            Description = "Líder em componentes de movimentação com polímeros de alto desempenho.",
                            Name = "Igus",
                            Picture = "/public/pictures/business/igus.jpg"
                        },
                        new
                        {
                            CodCompany = 5,
                            Description = "Empresa referência em climatização e engenharia ambiental.",
                            Name = "Munclair",
                            Picture = "/public/pictures/business/munclair.jpg"
                        });
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Lecture", b =>
                {
                    b.Property<int>("CodLecture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLecture"));

                    b.Property<DateTime>("DatetimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatetimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Speaker")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodLecture");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            CodLecture = 1,
                            DatetimeEnd = new DateTime(2024, 6, 2, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 2, 19, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Engenharia de Produção e Suas Aplicações",
                            Picture = "/public/pictures/lectures/mirna_bonfim.jpg",
                            Room = "H324",
                            Speaker = 1,
                            Title = "Engenharia de Produção e Suas Aplicações"
                        },
                        new
                        {
                            CodLecture = 2,
                            DatetimeEnd = new DateTime(2024, 6, 2, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 2, 19, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "CREA JOVEM",
                            Picture = "/public/pictures/lectures/jose_baptista.jpg",
                            Room = "H324",
                            Speaker = 3,
                            Title = "CREA JOVEM"
                        },
                        new
                        {
                            CodLecture = 3,
                            DatetimeEnd = new DateTime(2024, 6, 3, 22, 10, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 3, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tecnologia e Aplicações",
                            Picture = "/public/pictures/lectures/flavio_wallis.jpg",
                            Room = "H324",
                            Speaker = 2,
                            Title = "Tecnologia e Aplicações"
                        },
                        new
                        {
                            CodLecture = 4,
                            DatetimeEnd = new DateTime(2024, 6, 3, 22, 10, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 3, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soluções para Teste e Medição de RF",
                            Picture = "/public/pictures/lectures/jose_reis.jpg",
                            Room = "H324",
                            Speaker = 4,
                            Title = "Soluções p. Teste e Med. de RF"
                        },
                        new
                        {
                            CodLecture = 5,
                            DatetimeEnd = new DateTime(2024, 6, 4, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 4, 19, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Impressão 3D na manufatura 4.0",
                            Picture = "/public/pictures/lectures/joao_macluf.jpg",
                            Room = "H324",
                            Speaker = 5,
                            Title = "Impressao 3D na manufatura 4.0"
                        },
                        new
                        {
                            CodLecture = 6,
                            DatetimeEnd = new DateTime(2024, 6, 4, 22, 10, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 4, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Engenharia e energia: O futuro que já começou",
                            Picture = "/public/pictures/lectures/eduardo_emiliano.jpg",
                            Room = "H324",
                            Speaker = 6,
                            Title = "Engenharia e energia: O futuro que já começou"
                        },
                        new
                        {
                            CodLecture = 7,
                            DatetimeEnd = new DateTime(2024, 6, 5, 20, 50, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 5, 19, 10, 0, 0, DateTimeKind.Unspecified),
                            Description = "Venturus - O que é computação quântica e pra que serve?",
                            Picture = "/public/pictures/lectures/luiz-augusto.jpg",
                            Room = "A definir",
                            Speaker = 8,
                            Title = "O que é computação quântica e pra que serve?"
                        },
                        new
                        {
                            CodLecture = 8,
                            DatetimeEnd = new DateTime(2024, 6, 5, 22, 40, 0, 0, DateTimeKind.Unspecified),
                            DatetimeStart = new DateTime(2024, 6, 5, 20, 50, 0, 0, DateTimeKind.Unspecified),
                            Description = "Go Gamers - ESPM Escola Superior de Propaganda e Marketing",
                            Picture = "/public/pictures/lectures/fernando-matijewitsch.jpg",
                            Room = "H433",
                            Speaker = 7,
                            Title = "Marketing Aplicado às Engenharias"
                        });
                });

            modelBuilder.Entity("EngenhariasSenac.Models.LectureCertificate", b =>
                {
                    b.Property<int>("CodCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCertificate"));

                    b.Property<DateTime>("DatetimeGenerate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lecture")
                        .HasColumnType("int");

                    b.Property<int>("LectureNavigationCodLecture")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Student")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodCertificate");

                    b.HasIndex("LectureNavigationCodLecture");

                    b.ToTable("LectureCertificate");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.LectureLog", b =>
                {
                    b.Property<int>("CodLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLog"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Student")
                        .HasColumnType("int");

                    b.HasKey("CodLog");

                    b.ToTable("LectureLogs");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.LectureSpeaker", b =>
                {
                    b.Property<int>("CodSpeaker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodSpeaker"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodSpeaker");

                    b.ToTable("LectureSpeakers");

                    b.HasData(
                        new
                        {
                            CodSpeaker = 1,
                            Fullname = "Eng. Mirna Bonfim",
                            Linkedin = "https://www.linkedin.com"
                        },
                        new
                        {
                            CodSpeaker = 2,
                            Fullname = "Eng. Flavio Wallis",
                            Linkedin = "https://www.linkedin.com"
                        },
                        new
                        {
                            CodSpeaker = 3,
                            Fullname = "Eng. Jose Renato Baptista",
                            Linkedin = "https://www.linkedin.com"
                        },
                        new
                        {
                            CodSpeaker = 4,
                            Fullname = "Eng. Jose Reis",
                            Linkedin = "https://www.linkedin.com"
                        },
                        new
                        {
                            CodSpeaker = 5,
                            Fullname = "João Macluf",
                            Linkedin = "https://www.linkedin.com"
                        },
                        new
                        {
                            CodSpeaker = 6,
                            Fullname = "Eng. Eduardo Emiliano",
                            Linkedin = "https://www.linkedin.com"
                        },
                        new
                        {
                            CodSpeaker = 7,
                            Fullname = "Fernando Matijewitsch",
                            Linkedin = "https://www.linkedin.com/in/fernando-matijewitsch/"
                        },
                        new
                        {
                            CodSpeaker = 8,
                            Fullname = "Luiz Augusto",
                            Linkedin = "https://www.linkedin.com/in/econofisico/"
                        });
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectAssessment", b =>
                {
                    b.Property<int>("CodAssessment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAssessment"));

                    b.Property<decimal>("Assessment")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("EvaluatedProject")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudentEvaluator")
                        .HasColumnType("int");

                    b.HasKey("CodAssessment");

                    b.ToTable("ProjectAssessments");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectAttachment", b =>
                {
                    b.Property<int>("CodAttachment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAttachment"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectTeam")
                        .HasColumnType("int");

                    b.HasKey("CodAttachment");

                    b.ToTable("ProjectAttachment");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectNote", b =>
                {
                    b.Property<int>("CodAssessment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAssessment"));

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("EvaluateType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("EvaluatedProject")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TeacherEvaluator")
                        .HasColumnType("int");

                    b.HasKey("CodAssessment");

                    b.ToTable("ProjectNotes");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectTeam", b =>
                {
                    b.Property<int>("CodTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTeam"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Leader")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CodTeam");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Student", b =>
                {
                    b.Property<int>("CodStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodStudents"));

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdSenac")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PointMaterial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectTeam")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("CodStudents");

                    b.HasIndex("IdSenac")
                        .IsUnique()
                        .HasFilter("[IdSenac] IS NOT NULL");

                    b.HasIndex("InstitutionalEmail")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Teacher", b =>
                {
                    b.Property<int>("CodTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTeacher"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstitutionalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodTeacher");

                    b.HasIndex("InstitutionalEmail")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.LectureCertificate", b =>
                {
                    b.HasOne("EngenhariasSenac.Models.Lecture", "LectureNavigation")
                        .WithMany()
                        .HasForeignKey("LectureNavigationCodLecture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
