// <auto-generated />
using System;
using EngenhariasSenac.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngenhariasSenac.Migrations
{
    [DbContext(typeof(EngenhariasSenacContext))]
    partial class EngenhariasSenacContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EngenhariasSenac.Models.BusinessAssessment", b =>
                {
                    b.Property<int>("CodAssessment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAssessment"));

                    b.Property<decimal>("Assessment")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyEvaluated")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudentEvaluator")
                        .HasColumnType("int");

                    b.HasKey("CodAssessment");

                    b.ToTable("BusinessAssessment");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Committee", b =>
                {
                    b.Property<int>("CodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodId"));

                    b.Property<int>("IdSenac")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodId");

                    b.HasIndex("IdSenac")
                        .IsUnique();

                    b.ToTable("Committee");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Companies", b =>
                {
                    b.Property<int>("CodCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCompany"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodCompany");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ExtraPoint", b =>
                {
                    b.Property<int>("CodExtraPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodExtraPoint"));

                    b.Property<string>("Discipline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Point")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CodExtraPoint");

                    b.HasIndex("StudentId");

                    b.ToTable("ExtraPoints");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Lecture", b =>
                {
                    b.Property<int>("CodLecture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLecture"));

                    b.Property<DateTime>("DatetimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatetimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Speaker")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodLecture");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.LectureLog", b =>
                {
                    b.Property<int>("CodLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLog"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Student")
                        .HasColumnType("int");

                    b.HasKey("CodLog");

                    b.ToTable("LectureLogs");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.LectureSpeaker", b =>
                {
                    b.Property<int>("CodSpeaker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodSpeaker"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodSpeaker");

                    b.ToTable("LectureSpeakers");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectAssessment", b =>
                {
                    b.Property<int>("CodAssessment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAssessment"));

                    b.Property<decimal>("Assessment")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EvaluatedProject")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudentEvaluator")
                        .HasColumnType("int");

                    b.HasKey("CodAssessment");

                    b.ToTable("ProjectAssessments");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectAttachment", b =>
                {
                    b.Property<int>("CodAttachment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAttachment"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectTeam")
                        .HasColumnType("int");

                    b.HasKey("CodAttachment");

                    b.ToTable("ProjectAttachment");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectNote", b =>
                {
                    b.Property<int>("CodAssessment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAssessment"));

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluateType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("EvaluatedProject")
                        .HasColumnType("int");

                    b.Property<int>("TeacherEvaluator")
                        .HasColumnType("int");

                    b.HasKey("CodAssessment");

                    b.ToTable("ProjectNotes");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ProjectTeam", b =>
                {
                    b.Property<int>("CodTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTeam"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Leader")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PresentationDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("PresentationsRoom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Semester")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CodTeam");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Student", b =>
                {
                    b.Property<int>("CodStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodStudents"));

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdSenac")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PointMaterial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectTeam")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("CodStudents");

                    b.HasIndex("IdSenac")
                        .IsUnique()
                        .HasFilter("[IdSenac] IS NOT NULL");

                    b.HasIndex("InstitutionalEmail")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.Teacher", b =>
                {
                    b.Property<int>("CodTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTeacher"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstitutionalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodTeacher");

                    b.HasIndex("InstitutionalEmail")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.TeachersPanel", b =>
                {
                    b.Property<int>("CodPanel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPanel"));

                    b.Property<int>("CodTeacher")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PresentationDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("PresentationsRoom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CodPanel");

                    b.HasIndex("CodTeacher");

                    b.ToTable("TeachersPanel");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.ExtraPoint", b =>
                {
                    b.HasOne("EngenhariasSenac.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EngenhariasSenac.Models.TeachersPanel", b =>
                {
                    b.HasOne("EngenhariasSenac.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("CodTeacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
